name: get_calley_v1
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  http: ^0.13.6
  fl_chart: ^0.64.0
  pie_chart: ^5.4.0
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


